import{db as l,auth as a,googleAuthProvider as L}from"./firebase-setup.js";import{DB_PATHS as c,STORAGE_KEYS as t,APP_CONSTANTS as m}from"./rules.js";import{handleSignupGoogle as w,handleRenewal as A}from"./payment.js";import{showToast as i}from"./ui.js";let p=!1,d=null,f=!1;function R(){const e=document.getElementById("auth-modal");!e||e.classList.contains("hidden")||(e.classList.add("opacity-0"),window.setTimeout(()=>{e.classList.add("hidden"),e.classList.remove("flex","opacity-0"),document.body.style.overflow=""},220))}function b(e){if(!e)return null;try{return JSON.parse(e)}catch{return localStorage.removeItem(t.USER_AUTH),null}}function S(){return b(localStorage.getItem(t.USER_AUTH))}function g(e){return String(e?.membership_status||"").toLowerCase()===m.STATUS_ACTIVE}function h(e,o){const r={...o,uid:e,dbPath:`${c.USERS}/${e}`,role:m.ROLE_USER};localStorage.setItem(t.USER_AUTH,JSON.stringify(r))}async function T(){if(!f){if(f=!0,!a){console.warn("Auth module unavailable.");return}if(!(typeof firebase>"u"||!firebase.auth||!firebase.auth.Auth||!firebase.auth.Auth.Persistence))try{await a.setPersistence(firebase.auth.Auth.Persistence.LOCAL)}catch(e){console.warn("Unable to enforce LOCAL auth persistence:",e)}}}async function _(e){const o=sessionStorage.getItem(t.LOGIN_IN_PROGRESS);if(!e){if(o==="active")return;localStorage.removeItem(t.USER_AUTH),s();return}if(o==="done"){sessionStorage.removeItem(t.LOGIN_IN_PROGRESS),s();return}if(l){try{const r=await l.ref(`${c.USERS}/${e.uid}`).once("value");if(r.exists()){const n=r.val();g(n)?h(e.uid,n):localStorage.removeItem(t.USER_AUTH)}else{const n=S();(!n||n.uid!==e.uid)&&localStorage.removeItem(t.USER_AUTH)}}catch(r){console.error("Auth state sync error:",r)}s()}}function G(){if(p)return s(),d;if(p=!0,T(),!!a)return d=a.onAuthStateChanged(e=>{_(e)}),window.addEventListener("auth-updated",s),s(),d}function s(){const e=S(),o=document.getElementById("user-greeting"),r=document.getElementById("nav-auth-btn"),n=document.getElementById("premium-badge"),u=document.getElementById("profile-menu-content");if(r)if(e){const v=(e.name||"Member").split(" ")[0],E=e.name||"Premium Member";o&&(o.classList.add("hidden"),o.innerHTML=""),n&&(n.classList.add("hidden"),n.classList.remove("flex")),r.className="auth-strip-btn profile-strip-btn",r.setAttribute("aria-label","Open profile menu"),r.setAttribute("aria-expanded","false"),r.innerHTML=`
            <span class="profile-strip-user">
                <span class="profile-avatar" aria-hidden="true">
                    <svg width="17" height="17" viewBox="0 0 24 24" fill="none">
                        <path d="M12 12a4.2 4.2 0 1 0 0-8.4 4.2 4.2 0 0 0 0 8.4Z" stroke="currentColor" stroke-width="1.8"/>
                        <path d="M4.5 20.4a7.9 7.9 0 0 1 15 0" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
                    </svg>
                </span>
                <span class="profile-name">${I(v)}</span>
            </span>
            <span class="profile-premium">
                <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
                    <path d="M4 8.5 7.8 12l4.2-6 4.2 6L20 8.5 18 18H6L4 8.5Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                Premium
            </span>
        `,u&&(u.innerHTML=`
                <p class="profile-label">Signed in as</p>
                <p class="profile-value">${I(E)}</p>
            `)}else r.className="auth-strip-btn auth-cta-btn",r.removeAttribute("aria-label"),r.removeAttribute("aria-expanded"),r.innerHTML="LOGIN / SIGNUP",u&&(u.innerHTML="")}function I(e){return String(e).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}async function P(){if(!a||!l)return i("System unavailable. Please refresh.","error"),!1;try{sessionStorage.setItem(t.LOGIN_IN_PROGRESS,"active");const o=(await a.signInWithPopup(L)).user;if(!o)return sessionStorage.removeItem(t.LOGIN_IN_PROGRESS),i("Unable to identify your Google account. Please try again.","error"),!1;const r=await l.ref(`${c.USERS}/${o.uid}`).once("value"),n=r.exists()?r.val():null;return n?g(n)?(h(o.uid,n),sessionStorage.setItem(t.LOGIN_IN_PROGRESS,"done"),s(),R(),i(`Welcome back, ${(n.name||"Member").split(" ")[0]}!`,"success"),window.dispatchEvent(new Event("auth-updated")),!0):(sessionStorage.removeItem(t.LOGIN_IN_PROGRESS),window.confirm("Your premium access has expired. Would you like to renew?")?(A(o.uid,n),i("Renewal checkout opened. Complete payment to restore access.","info")):(localStorage.removeItem(t.USER_AUTH),s(),i("Renewal is required before access is restored.","info")),!1):(sessionStorage.removeItem(t.LOGIN_IN_PROGRESS),w(o),!1)}catch(e){return sessionStorage.removeItem(t.LOGIN_IN_PROGRESS),e.code!=="auth/popup-closed-by-user"&&(console.error("Google Auth Error",e),i("Login interrupted. Please ensure popups are enabled and try again.","error")),!1}}async function C(){if(!a)return window.dispatchEvent(new Event("auth-updated")),!0;try{await a.signOut()}catch(e){console.error("Sign-out error:",e)}localStorage.removeItem(t.USER_AUTH),sessionStorage.removeItem(t.CACHED_CONTENT),sessionStorage.removeItem(t.CONTENT_TIMESTAMP),sessionStorage.removeItem(t.CACHED_SETTINGS),sessionStorage.removeItem(t.SETTINGS_TIMESTAMP),sessionStorage.removeItem(t.LOGIN_IN_PROGRESS),s(),i("You have been signed out.","info",2200),window.dispatchEvent(new Event("auth-updated"))}export{S as getLocalUser,G as initAuthListener,P as loginWithGoogle,C as logoutUser,s as updateAuthUI};
