import{db as y}from"./firebase-setup.js";import{DB_PATHS as T,STORAGE_KEYS as g,CACHE_TTL as B}from"./rules.js";import{getLocalUser as M}from"./auth.js";import{showToast as h}from"./ui.js";const f=15;let m=[],c=[],d=f,E=null,w=!1;async function D(){const e=document.getElementById("content-grid"),n=document.getElementById("loading-state");if(!e||!n)return;const s=sessionStorage.getItem(g.CACHED_CONTENT),o=sessionStorage.getItem(g.CONTENT_TIMESTAMP),i=Date.now();if(s&&o&&i-parseInt(o,10)<B.CONTENT)try{L(JSON.parse(s),e),n.classList.add("hidden");return}catch{sessionStorage.removeItem(g.CACHED_CONTENT),sessionStorage.removeItem(g.CONTENT_TIMESTAMP)}if(!y){C(e),n.classList.add("hidden");return}try{let t=null;try{t=await y.ref(T.CONTENT_META).once("value"),t.exists()||(t=null)}catch{t=null}if(t||(t=await y.ref(T.CONTENT).once("value")),t.exists()){const r=t.val();sessionStorage.setItem(g.CACHED_CONTENT,JSON.stringify(r)),sessionStorage.setItem(g.CONTENT_TIMESTAMP,String(Date.now())),L(r,e)}else x(e)}catch(t){console.error("Content load error:",t),C(e),h("Unable to load the library right now. Please retry shortly.","error")}n.classList.add("hidden")}function x(e){const n=document.getElementById("txt-grid");n&&(e.classList.remove("hidden"),n.innerHTML=`
        <div class="empty-list-card">
            <p style="font-size: 1.4rem; margin-bottom: 0.5rem;">The library is being prepared.</p>
            <p style="font-size: 0.95rem; font-family: 'Manrope', sans-serif; font-style: normal; color: var(--ink-muted);">New articles will appear here soon.</p>
        </div>
    `)}function C(e){const n=document.getElementById("txt-grid");n&&(e.classList.remove("hidden"),n.innerHTML=`
        <div class="empty-list-card">
            <p style="font-size: 1.4rem; margin-bottom: 0.5rem;">Unable to load the library.</p>
            <p style="font-size: 0.95rem; font-family: 'Manrope', sans-serif; font-style: normal; color: var(--ink-muted);">Please check your connection and refresh.</p>
        </div>
    `)}function L(e,n){E=n,m=Object.keys(e).map(i=>({...e[i],_key:i})).filter(i=>i&&i.is_published),N();const s=document.getElementById("content-search-input"),o=s?s.value.trim():"";d=f,v(o)}function N(){if(w)return;const e=document.getElementById("content-search-input"),n=document.getElementById("clear-search-btn"),s=document.getElementById("pdf-load-more-btn"),o=document.getElementById("search-suggestions");e&&(e.addEventListener("input",()=>{d=f;const t=e.value.trim();v(t),S(t)}),e.addEventListener("focus",()=>{S(e.value.trim())}),e.addEventListener("keydown",t=>{t.key==="Escape"&&u()})),s&&(s.addEventListener("click",()=>{s.classList.add("is-loading"),setTimeout(()=>{d+=f,b(),s.classList.remove("is-loading")},350)}),s.addEventListener("keydown",t=>{(t.key==="Enter"||t.key===" ")&&(t.preventDefault(),s.click())}));const i=t=>{"ontouchstart"in window||navigator.maxTouchPoints>0?t.blur():t.focus()};n&&e&&n.addEventListener("click",()=>{e.value="",d=f,v(""),u(),i(e)}),o&&e&&(o.addEventListener("click",t=>{const r=t.target.closest(".suggestion-item");if(!r)return;const a=r.getAttribute("data-type"),l=r.getAttribute("data-val")||"";a==="article"?(u(),I(l)):a==="category"&&(e.value=l,d=f,v(l),u(),i(e))}),document.addEventListener("click",t=>{const r=e.closest(".search-shell");r&&(r.contains(t.target)||u())})),w=!0}function v(e){const n=e.toLowerCase();n?c=m.filter(s=>`${s.title||""} ${s.category||""} ${s.type||""}`.toLowerCase().includes(n)):c=[...m],b(),_(e)}function b(){const e=document.getElementById("txt-grid"),n=document.getElementById("pdf-load-more-btn"),s=document.getElementById("content-search-input"),o=s&&s.value.trim().length>0;if(!E||!e)return;e.innerHTML="",E.classList.remove("hidden");const i=o?c:c.slice(0,d);if(i.forEach(t=>{e.appendChild($(t))}),i.length||(e.innerHTML=A("No articles match your search.")),n)if(o)n.classList.add("hidden");else if(c.length-d>0){const r=n.querySelector(".load-more-text");r&&(r.textContent="Show More Articles"),n.classList.remove("hidden")}else n.classList.add("hidden")}function _(e){const n=document.getElementById("clear-search-btn"),s=document.getElementById("search-result-meta");if(n&&(e?n.classList.remove("hidden"):n.classList.add("hidden")),s)if(e)s.innerText=`${c.length} result${c.length!==1?"s":""} for "${e}"`;else{const o=m.length;s.innerText=o>0?`${o} articles in the library`:"Curated knowledge library"}}function $(e){const n=document.createElement("div");n.className="content-card",n.setAttribute("data-key",e._key),n.onclick=()=>I(e._key);const s=e.category?p(e.category):"";return n.innerHTML=`
        <div class="file-list-row">
            <div class="file-list-title-shell">
                <h3 class="file-list-title">${p(e.title||"Untitled")}</h3>
                <div style="display: flex; gap: 8px; align-items: center; margin-top: 4px;">
                    ${s?`<span class="file-list-category" style="margin-top: 0;">${s}</span>`:""}
                    ${e.is_free?'<span class="file-list-category" style="margin-top: 0; background: var(--accent-mint); color: #000; font-weight: 700; border: none;">Free Demo</span>':""}
                </div>
            </div>
            <span class="file-list-arrow" aria-hidden="true">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
            </span>
        </div>
    `,n}function A(e){return`
        <div class="empty-list-card">
            ${p(e)}
        </div>
    `}function S(e){const n=document.getElementById("search-suggestions");if(!n)return;const s=e.toLowerCase();if(!s||s.length<2){u();return}const o=[],i=new Set;if(m.forEach(t=>{const r=t.title?String(t.title).trim():"",a=t.category?String(t.category).trim():"";r&&r.toLowerCase().includes(s)&&!i.has("t:"+r.toLowerCase())&&(i.add("t:"+r.toLowerCase()),o.length<6&&o.push({label:r,type:"article",data:t._key})),a&&a.toLowerCase().includes(s)&&!i.has("c:"+a.toLowerCase())&&(i.add("c:"+a.toLowerCase()),o.length<6&&o.push({label:a,type:"category",data:a}))}),!o.length){u();return}n.innerHTML=o.map(t=>`
            <button type="button" class="suggestion-item premium-suggestion" data-type="${t.type}" data-val="${p(t.data||"")}">
                <span class="suggestion-dot" style="background: ${t.type==="article"?"var(--accent-mint)":"var(--accent-yellow)"}"></span>
                <span class="suggestion-text">${p(t.label)}</span>
                <span class="suggestion-badge">${t.type==="article"?"Article":"Category"}</span>
            </button>
        `).join(""),n.classList.remove("hidden")}function u(){const e=document.getElementById("search-suggestions");e&&(e.classList.add("hidden"),e.innerHTML="")}function p(e){return String(e).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}async function I(e){const n=m.find(r=>r._key===e),s=n&&n.is_free===!0,o=M();if(!s){if(!o){window.dispatchEvent(new Event("open-auth-modal"));return}if(o.membership_status!=="active"){h("Your premium access is inactive. Please renew to continue.","info");return}}if(n&&n.file_url){const r=n.file_url,a=r.includes("?")?r+"&id="+e:r+"?id="+e;window.open(a,"ReaderTab");return}const i=document.querySelector(`.content-card[data-key="${e}"]`),t=i?i.querySelector(".file-list-arrow"):null;t&&(t.innerHTML='<span class="card-loading-dot"></span>');try{const r=await y.ref(`${T.CONTENT_URLS}/${e}`).once("value");if(r.exists()){const a=r.val(),l=typeof a=="string"?a:a.file_url;if(l){const k=l.includes("?")?l+"&id="+e:l+"?id="+e;window.open(k,"ReaderTab")}else h("Content link is unavailable. Please contact support.","error")}else h("Content not found. Please contact support.","error")}catch(r){console.error("Secure URL fetch error:",r),h("Unable to load content. Please try again.","error")}t&&(t.innerHTML='<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg>')}export{D as loadContent};
